/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DatamapVisualizer: typeof import('./components/DatamapVisualizer.vue')['default']
    ThreeJs: typeof import('./components/ThreeJs.vue')['default']
    TimeController: typeof import('./components/TimeController.vue')['default']
    ViewSelector: typeof import('./components/ViewSelector.vue')['default']
    YaraCore: typeof import('./components/YaraCore.vue')['default']
    YBtn: typeof import('./components/YBtn.vue')['default']
    YClock: typeof import('./components/YClock.vue')['default']
    YDivider: typeof import('./components/YDivider.vue')['default']
    YIcon: typeof import('./components/YIcon.vue')['default']
    YInteractionSection: typeof import('./components/YInteractionSection.vue')['default']
    YOverlay: typeof import('./components/YOverlay.vue')['default']
    YPannel: typeof import('./components/YPannel.vue')['default']
    YSelect: typeof import('./components/YSelect.vue')['default']
  }
}
