/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DatamapVisualizer: typeof import('./components/DatamapVisualizer.vue')['default']
    Overlay: typeof import('./components/Overlay.vue')['default']
    Pannel: typeof import('./components/Pannel.vue')['default']
    Table: typeof import('./components/Table.vue')['default']
    ThreeJs: typeof import('./components/ThreeJs.vue')['default']
    ViewSelector: typeof import('./components/ViewSelector.vue')['default']
    Yara: typeof import('./components/Yara.vue')['default']
    YDivider: typeof import('./components/YDivider.vue')['default']
    YIcon: typeof import('./components/YIcon.vue')['default']
    YSelect: typeof import('./components/YSelect.vue')['default']
  }
}
