name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build (production & demo)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci

      - name: Run build for demo
        run: npm run build:demo
      - name: Run build for production
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: [build]
    name: Test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run test

  lint:
    runs-on: ubuntu-latest
    needs: [build]
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

  type-check:
    runs-on: ubuntu-latest
    needs: [build]
    name: Type Check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci

      - name: Run Typescript type check
        run: npm run lint

  update-parent:
    name: Update Parent
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
        with:
          repository: marcyleite/yara
          token: ${{ secrets.PARENT_REPO_GITHUB_TOKEN  }}
          submodules: true

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add --all

          git commit -m ":truck: Update web client parent" || echo "No changes to commit"
          git push
