name: Release

permissions:
  contents: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    name: Analyze

    outputs:
      version: ${{ steps.export.outputs.version }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci

      - name: Run analyze
        run: npm run release-analyze

      - name: Export version
        id: export
        run: echo "version=$(cat version)" >> "$GITHUB_OUTPUT"

      - name: Export CHANGELOG.md
        uses: actions/upload-artifact@v4
        with:
          name: notes
          path: notes

  update:
    name: Update
    runs-on: ubuntu-latest
    needs: [analyze]
    env:
      VERSION: ${{ needs.analyze.outputs.version }}
    if: ${{ needs.analyze.outputs.version != '' }}

    outputs:
      version: ${{ steps.export.outputs.version }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download CHANGELOG
        uses: actions/download-artifact@v4
        with:
          name: notes

      - run: mv notes CHANGELOG.md

      - name: Update package.json version
        run: npm version --no-git-tag-version $VERSION

      - name: Export CHANGELOG.md
        uses: actions/upload-artifact@v4
        with:
          name: CHANGELOG
          path: CHANGELOG.md

      - name: Export package.json
        uses: actions/upload-artifact@v4
        with:
          name: package-json
          path: package.json

      - name: Export version
        id: export
        run: echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  release-gh:
    name: Publish tags and create GH Release
    runs-on: ubuntu-latest
    needs: [update]

    env:
      VERSION: ${{ needs.update.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Download CHANGELOG
        uses: actions/download-artifact@v4
        with:
          name: CHANGELOG

      - name: Download package.json
        uses: actions/download-artifact@v4
        with:
          name: package-json

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md package.json
          git commit -m "🔖 Release version $VERSION" -m "[skip ci]"

      - name: Create tag
        run: git tag v$VERSION

      - name: Push changes
        run: |
          git push
          git push --tags

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: gh release create v$VERSION -F CHANGELOG.md

  release-image:
    needs: [update]
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ needs.update.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            marcyleite/yara-web-client:${{ needs.update.outputs.version }}
            marcyleite/yara-web-client:latest

  deploy-demo:
    needs: [update]

    runs-on: ubuntu-latest
    name: Deploy demo (GitHub Pages)

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download package.json
        uses: actions/download-artifact@v4
        with:
          name: package-json

      - run: npm ci

      - name: Build demo
        run: npm run build:demo

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
