name: Release

on:
  push:
    branches:
      - release

jobs:
  update-files:
    runs-on: ubuntu-latest
    needs: [analyze]

    steps:
      - name: Extract version
        run: |
          export VERSION=$(grep '"version":' package.json | sed -E 's/.*"version": "([^"]+)".*/\1/')

      - name: Create PR
        run: |
          PR_EXISTS=$(gh pr list --base "main" --head "release" --json number --jq 'length')
          if [ "$PR_EXISTS" -eq 0 ]; then
            gh pr create --base "main" --head "release" --title "🔖 Release version $VERSION" --body-file CHANGELOG.md
          else
            PR_NUMBER=$(gh pr list --base "main" --head "release" --json number --jq '.[0].number')
            gh pr edit "$PR_NUMBER" --title "🔖 Release version $VERSION" --body-file CHANGELOG.md
          fi
