name: Trunk Merge

on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  update-parent:
    name: Update Parent
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    env:
      MESSAGE: ${{ github.event.head_commit.message }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: marcyleite/yara
          token: ${{ secrets.PARENT_REPO_GITHUB_TOKEN  }}
          submodules: true

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add --all

          git commit -m "$MESSAGE" || echo "No changes to commit"
          git push
