name: Trunk Merge

on:
  pull_request:
    branches:
      - main
      - next-release

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build (production & demo)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: npm install
        run: npm ci

      - name: Run build for demo
        run: npm run build:demo
      - name: Run build for production
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: [build]
    name: Test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: npm install
        run: npm ci

      - name: Run lint
        run: npm run test

  lint:
    runs-on: ubuntu-latest
    needs: [build]
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: npm install
        run: npm ci

      - name: Run lint
        run: npm run lint

  type-check:
    runs-on: ubuntu-latest
    needs: [build]
    name: Type Check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: npm install
        run: npm ci

      - name: Run Typescript type check
        run: npm run lint
